backend:
  name: github
  repo: rchrdnsh/arrow-gtp
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
